### ISSUE TITLE
Source code of BSC Multicall contract

### ISSUE THREAD

**Issue by lcswillems** [joshstevens19/ethereum-multicall#10]
Hi Josh,

The BSC Multicall contract used by ethereum-multicall is: https://bscscan.com/address/0xAf379C844f87A7b47EE6fe5E4a9720988EaEA0AF

Are you the one who published the contract? If yes, could you also publish the source? I tried to publish it but it didn't work.

**Comment by joshstevens19** [comment]
Hey thanks for the issue. Yes I did. Course il get it verified. I am away on vacation until next Monday but il do it once back. Thanks

**Comment by lcswillems** [comment]
Okay, thanks a lot!!

**Comment by joshstevens19** [comment]
Hey no clue where i created that contract from I could not verify it either, think it was due to whitespace anyway I gave up and deployed a new contract here - 0xC50F4c1E81c873B2204D7eFf7069Ffec6Fbe136D which has the code verified https://bscscan.com/address/0xC50F4c1E81c873B2204D7eFf7069Ffec6Fbe136D#code 

2.6.1 now has that code change in so it will point to that now! 

Sorry for delay have been away.
Thanks

**Comment by lcswillems** [comment]
Thanks a lot!! And not problem for the delay, it is normal!
