### ISSUE TITLE
Getting "UnhandledPromiseRejectionWarning: Error: Returned error: out of gas" error

### ISSUE THREAD

**Issue by lolosj** [joshstevens19/ethereum-multicall#14]
On a multicall call on the bsc contract, I get this error : UnhandledPromiseRejectionWarning: Error: Returned error: out of gas
The call was working before, didn't change any. Have any idea where this issue comes from and how I can solve it ?

**Comment by joshstevens19** [comment]
Hey that is odd is there a way you can setup a repo so I can recreate?

**Comment by lolosj** [comment]
I identified the error. I solved it.

The problem is specefic to pancakeswap. 

My program scans pools from pancakeswap master contract, and it seems that they added a farm recently :  

https://bscscan.com/address/0x73feaa1ee314f8c655e354234017be2193c9e24e#readContract

Methode PoolInfo, input : 444.
--> lpToken   address :  0x0000000000000000000000000000000000000064

My code was programmatically asking infos to this contract. The error was coming from this. 

I excluded this farm before calling the multicall contract, and the bug disappeared.

**Comment by lolosj** [comment]
Awesome code by the way, I use ethereum-multicall a lot on BSC and it works like a charm.

**Comment by joshstevens19** [comment]
ahhh awesome glad its not broken for you then. Glad the lib makes your life easier!!! will close now thanks for your kind words!

**Comment by joshstevens19** [comment]
Oh just a hint you can use tryAggregate in the multicall options so it doesn’t all fail if 1 call fails. May be worth you adding by default it is off aka if 1 fails it all fails > https://github.com/joshstevens19/ethereum-multicall#try-aggregate worth using this it’s a lot easier to tell what’s gone wrong.

**Comment by lolosj** [comment]
My friend I already use tryAggregate : true.

I was able to reproduce a code which will throw an error. I think it's unintended but I am not sure.

I will upload it on github and let you know when it's done. Maybe it will be helpful for your project.

**Comment by lolosj** [comment]
Here it is : https://github.com/lolosj/ethereum-multicall-outofgaserror

Please let me know if you have an explanation, I am curious.

**Comment by lolosj** [comment]
Note : even if we use the same method in the 2 calls, it will throw an error when 3 or more calls, and no error with 1, or 2 call.

Like this : 

    contractCallContext.push({
       reference: 'pancake_farm_444',
       contractAddress: contractAddress,
       abi : TokenABI,
       calls : [
        { reference: 'token0_pancake_farm_444', methodName: 'token0' },
        { reference: 'token0_pancake_farm_444', methodName: 'token0' },
        ]
     });

No error with the exemple above.

Error with the example below : 

    contractCallContext.push({
       reference: 'pancake_farm_444',
       contractAddress: contractAddress,
       abi : TokenABI,
       calls : [
        { reference: 'token0_pancake_farm_444', methodName: 'token0' }, 
        
        { reference: 'token0_pancake_farm_444', methodName: 'token0' },

        { reference: 'token0_pancake_farm_444', methodName: 'token0' },
           ]
     });

Ain't that strange ?

**Comment by joshstevens19** [comment]
this is very strange! This seems to be binance nodes doing this and not the code itself. It seems if you get over 2 bad internal calls in the multicall contract anymore then the node will throw and say out of gas (generic exception). I have run this code against ethers and web3 and its nothing to do with the lib itself. I have also run this code against 30 success calls and it runs fine. 

I always get ` success: false` on both `token0_pancake_farm_444` and `token0_pancake_farm_444` aka they are failing even when I only do the `multicallFunction` itself. This would normally mean your contract is throwing an error or something is going wrong in `0x0000000000000000000000000000000000000064` or the ABI is wrong. `0x0000000000000000000000000000000000000064` is not verified on BSC so I could not look at the code. 

![image](https://user-images.githubusercontent.com/18472422/129332077-9213af09-bbbf-4299-8643-e244d59ae771.png)

My suggestion is to get the calls you're calling on the contract to be mapped correctly aka returning `success: true`  then your error should go away.

I can not fix this internal thing ethereum must do it's out of the scope of my lib but getting simple readme info like that should never fail. If this is dynamic code and it has to call incorrect stuff now and again you will have to try catch it and if it's entering into your catch you can assume everything has failed due to the constraint explain above. 

Let me know if you want me to look at the contract if you verify it on BSC. 

Thanks

**Comment by lolosj** [comment]
OK. If you can't do anything about it then forget it !
I found another solution in my project (I exclude non existing contracts before the call).
But the fact that the error is thrown when 2+ method calls and not with 1 or 2 is quite strange :)

Probably BSC specific.

**Comment by joshstevens19** [comment]
yes, it is very odd.. its the node throwing this not the code itself hence why I can not handle it. As said it's only on the edge case if the first 3 calls are success false. No clue why the node throws it out but that is to do with BSC itself and out of scope from the multicall code, all the multicall code knows is the node has thrown which if you look at the code is impossible as its in a try catch. Only thing which can override that is some internal management on the BSC itself. 

Glad you got a work around sorry I couldn't help more aka putting in a fix for you on my end.
