### ISSUE TITLE
Please use the "new" keyword to instantiate a web3.eth.Contract() object

### ISSUE THREAD

**Issue by bthaile** [joshstevens19/ethereum-multicall#3]
`rror: Please use the "new" keyword to instantiate a web3.eth.Contract() object!` getting this error when using newest version of ethereum-multicall

![image](https://user-images.githubusercontent.com/3970376/108738629-71cef780-74f9-11eb-9607-c04d6a9eee29.png)

I think just putting `new` will fix it

![image](https://user-images.githubusercontent.com/3970376/108738776-91662000-74f9-11eb-82c6-1d0648afb5d0.png)

**Comment by joshstevens19** [comment]
Hey thanks for raising the issue. 

You pass multicall the web3 instance multicall itself doesn’t have web3 installed, have you upgraded your web3 version? I have just looked and it seems they have shipped 1.3.4 19 days ago I’m guessing they accidentally did a breaking change with how you create a new contract instance. 

Be great to know what web3 version is in your lock file and then I can make sure old versions of web3 do not break when I do the fix. If it does I will have to open a issue on web3.js because that kind of breaking change doesn’t sit well.

thanks

**Comment by joshstevens19** [comment]
That said it looks like it should be “new” anyhow with the old versions, so think this is my error. I will take a look tomorrow morning and publish a fix for you tomorrow. That other info will still be great. Cheers

**Comment by joshstevens19** [comment]
Hey this is now fixed and 2.0.2 multicall should work for you

https://github.com/joshstevens19/ethereum-multicall/commit/4df9def05d620d80b0d935ad71142e9d73ada12d

Let me know if you still have problems. Thanks
